name: galery_app
description: App de galería

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^3.0.0
  permission_handler: ^11.0.0
  video_player: ^2.8.1
  http: ^1.1.0
  share_plus: ^7.2.1
  photo_view: ^0.14.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1   # <--- Agregar esta línea
 

flutter:
  uses-material-design: true